### ISSUE TITLE
the process was stuck in "RUN KRIGING USING VESPER"

### ISSUE THREAD

**Issue by bayutwp** [CSIRO-Precision-Agriculture/PAT_QGIS_Plugin#40]
![image](https://user-images.githubusercontent.com/62225215/77533077-cb353d80-6ec8-11ea-9498-b80e141df1e3.png)
I already follow the guidance, but stuck in "RUN KRIGIN GUSING VESPER"

Could you please solve this problem?

**Comment by cratcliff** [comment]
@bayutwp The Block Grid/Vesper Grid must overlap with the csv file. Load both files and make sure they are sitting on top of each other.  If they do overlap then they are using different coordinate systems. Both the Block Grid/Vesper Grid and CSV coordinates must be in the same projected coordinate system.

The output coordinate system in the Clean, trim, normalise point data tool must match the coordinate system of the Block Grid/Vesper Grid. If you want to reproject your csv without removing any points due to the cleaning/trimming then match the parameter settings found at in the [PAT User Manual](http://nbviewer.jupyter.org/github/CSIRO-Precision-Agriculture/PAT_QGIS_Plugin/blob/master/pat/PAT_User_Manual.pdf#pagemode=bookmarks&view=Fit&page=16)  at the end of page 16.
